[package]
name = "bond"
version = "0.1.0"
authors = ["KCaverly <kylebcaverly@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
crossterm = "0.26.1"
ratatui = "0.24.0"
replicate-rs = "0.6.0"
serde = "1.0.193"
tokio = { version = "1.34.0", features = ["full"]}
