name: Build and Release on Linux
permissions:
  contents: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build_and_release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz

    outputs:
      - release_tag: ${{ steps.release.outputs.release_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ".bin"
          
      - name: Build project
        run: |
          cargo build --release --target ${{ matrix.target }}
          "./target/${{ matrix.target }}/release/archer"

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "target/${{ matrix.target }}/release/archer"
        env:
          RELEASE_TAG: ${{ github.ref }}

  publish_to_aur:
    name: "publish to aur"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        target:
          -x86_64-unknown-linux-gnu

    needs:
      - build_and_release

    steps:
      - uses: actions/checkout@v2
      
      - name: Generate PKGBUILD
        env:
          TARGET: ${{ matrix.target }}
          RELEASE_TAG: ${{ needs.build_and_release.outputs.release_tag }}
        run: ./ci/github-actions/generate-pkgbuild.py3
    
      - name: Publish archer to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.0.2
        with:
          pkgname: archer
          pkgbuild: ./pkgbuild/archer/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ needs.create_release.outputs.release_tag }}
